ALTER TABLE order_item MODIFY expiry_date DATE;

UPDATE order_item SET expiry_date=NULL;


INSERT INTO enumeration (IS_ACTIVE,CREATED_BY, VERSION, DESCRIPTION, ENUM_CODE, ENUM_TYPE) 
VALUES ( TRUE,'SEED',  1, 'Inpatient', 'INPATIENT', 'TREATMENT_ADMISSION_TYPE');


INSERT INTO enumeration (IS_ACTIVE,CREATED_BY, VERSION, DESCRIPTION, ENUM_CODE, ENUM_TYPE) 
VALUES ( TRUE,'SEED',  1, 'Outpatient', 'OUTPATIENT', 'TREATMENT_ADMISSION_TYPE');

ALTER TABLE patient_soap_note AUTO_INCREMENT=1000;