INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'�C','celsius','TEMPERATURE');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'�F','fahrenheit','TEMPERATURE');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'Bpm','beats per minute','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'cm','centimeters','LENGTH');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'feet','feet','LENGTH');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'inches','inches','LENGTH');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'Kg','kilogram','WEIGHT');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'lbs','pounds','WEIGHT');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'mg','milligram','WEIGHT');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'mm','millimeter','LENGTH');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'pg','picogram','LENGTH');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'Pm','pico meters','LENGTH');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'mmHg','mmHg','PRESSURE');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'units/L','units/l','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'x10E3/uL','x10e3/ul','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'x10E6/uL','x10e6/ul','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'�g/cm','microgram per centimeter','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'�g/L','�g/l','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'pg/mL','picogram per milliliter','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'mm Hg','millimeter mercury','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'mg/dL','milligrams per deciliter','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'g/dL','grams per deciliter','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'HPF','millex-hpf filter unit','OTHER');
INSERT INTO unit_of_measurement(IS_ACTIVE,VERSION,CODE,DESCRIPTION,UOM_TYPE) VALUES (1,0,'mEq/L','milligram per liter','OTHER');
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','ADP','Andoran Peseta','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','AED','United Arab Emirates Dirham','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','AFA','Afghani','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','ALL','Albanian Lek','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','AMD','Armenian Dram','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','ANG','West Indian Guilder','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','AOK','Angolan Kwanza','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','ARA','Argentinian Austral','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','ESP','Spanish Peseta','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','ETB','Ethiopian Birr','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','EUR','Euro','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','FIM','Finnish Mark','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','FJD','Fiji Dollar','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','FKP','Falkland Pound','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','INR','Indian Rupee','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','HKD','Hong Kong Dollar','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,'0','USD','American Dollar','CURRENCY_TYPE',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,0,'DAY','Day','PRODUCT',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,1,'MONTH','Month','PRODUCT',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,1,'YEAR','Year','PRODUCT',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,1,'STRIP','Strip','PRODUCT',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,1,'CARTON','Carton','PRODUCT',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,1,'HOURS','Hours','PRODUCT',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,1,'MINUTE','Minute','PRODUCT',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,1,'TABLET','Tablet','PRODUCT',NULL);
insert into unit_of_measurement (IS_ACTIVE, VERSION, CODE, DESCRIPTION, UOM_TYPE, DEACTIVATEDBY) values(NULL,1,'UNIT','Unit','PRODUCT',NULL);
