INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'HPI_VIEW','Hpi view','HPI view',12,1,'ENUM','HPI');

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PAST_HISTORY','Past history view','Past History View',12,2,'ENUM','PAST_HISTORY');

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'EXAMINATION','Examination view','Examination View',12,3,'ENUM','EXAMINATION');

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'MEDICATION_REPORT','Medication and rx in reports','Medication and Rx in Reports',12,4,'ENUM','MEDICATION_RX_REPORTS');

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PHCALERT_SOAP','phcalert_soap','Prompt PHCAlert on SOAP Sign-In',12,5,'CHECKBOX',NULL);

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PATIENT_TRACKING','patient_tracking','Need Patient Tracking in Sign-In',12,6,'CHECKBOX',NULL);

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'DIFF_DIAGNOSIS_SETUP','differential_diagnosis','Display Differential Diagnosis Setup',12,7,'CHECKBOX',NULL);

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PASTHISTORY_ALERT','pasthistory_alert','Display Past History alert while Sign-Out',12,8,'CHECKBOX',NULL);

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PATIENTSSN_SOAP','patientssn_soap','Display Patient SSN in SOAP Preview',12,9,'CHECKBOX',NULL);

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PATIENTREFPHYSICIAN_SOAP','patientrefPhysician_soap','Display Patient Ref.Physician in SOAP Preview',12,10,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'TREATMENTPLAN_RECOMMENDATION','multipletreatmentplan','Display Multiple Treatment Plan in Recommendation',12,11,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'NORMALSENTENCE_QAMODULES','normalsentence_qamodules','Display Default Normal Sentence in QA Modules',12,12,'CHECKBOX',NULL);

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PEDIATRICGRAPH_SOAPNOTES','pediatricgraph_soap','Display Pediatric Graph in SOAP Notes',12,13,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PROVIDER_VITAL_SIGNS','Vital_Signs','Provider Vital Signs',12,14,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PRACTICENAME_SOAP','practicename_soap','Display Practice  Name in SOAP Notes',12,15,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'LOCATIONNAME_SOAP','locationname_soap','Display Location  Name in SOAP Notes',12,16,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PROVIDER_BASE_TEMP','provider_template','Provider Base Template',12,17,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'ROS_VIEW','Ros view','ROS View',12,18,'ENUM','ROS_VIEW');


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'SOCIAL_HISTORY','Social history view','Social History View',12,19,'ENUM','SOCIAL_HISTORY_VIEW');


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'RECOMMENDATION_VIEW','Recommendation View','Recommendation View',12,20,'ENUM','RECOMMENDATION_VIEW');

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'DISPLAY_BMI','bmi','Display BMI',12,21,'CHECKBOX',NULL);

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PEDIATRIC_BMI','Pediatric_bmi','Display Pediatric BMI',12,22,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'DISPLAY_BSA','bsa','Display BSA',12,23,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'DISPLAY_SS_SIGNIN','ss_sign-in','Display SS while Sign-In',12,24,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'ABN_SERVICE_VERIFICATION','abn_verification','ABN Service Verification',12,25,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'BMI_BSA_VALUES','bmi_bsavalues','BMI and BSA Values in',12,26,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'DIAGNOSIS_TREESEARCH','diagnosis_treesearch','Diagnosis (ICD) Tree Search',12,27,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PRINTSOAPNOTE_SIGNOFF','soapnote_signoff','Print Soap Note After Sign-off',12,28,'CHECKBOX',NULL);

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PROVIDER_FAMILYHISTORY','family_history','Provider Family History',12,29,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'DEFAULTVALUE_VITALSIGN','defaultvalue_vital','Display Default Value in Vital sign',12,30,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'CPT_REFERRALLETTER','cptreferral_letter','Display CPT in Referral Letter',12,31,'CHECKBOX',NULL);



INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'DEA_RXREPORT','dea_rxreport','Display DEA in Rx Report',13,1,'CHECKBOX',NULL);

INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'LOCATIONDEANUMBER_RXREPORT','deanumber_rxreport','Display Location DEA number in Rx Report',13,2,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'STATELICENSE_RXREPORT','statelicense_rxreport','Display State License in Rx Report',13,3,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PROVIDERNAME_RXREPORT','providername_rxreport','Display Provider Name in Rx Report',13,4,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'PRACTICENAME_RXREPORT','practicename_rxreport','Display Practice Name in Rx Report',13,5,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'LOCATIONNAME_RXREPORT','locationname_rxreport','Display Location Name in Rx Report',13,6,'CHECKBOX',NULL);


INSERT INTO preference_definition(VERSION,CREATED_BY,CREATE_TX_TIMESTAMP,NAME,description,`label`,PREFERENCE_GROUP_DEFINITION_ID,SEQ_NUM,FIELD_TYPE,FIELD_VALUE)
VALUES (1,'seed',NOW(),'NPINUMBER_RXREPORT','npinumber_rxreport','Display NPI Number in Rx Report',13,7,'CHECKBOX',NULL);
