insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LE','Left Eye');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RE','Right Eye');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LER','Left Ear');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RER','Right Ear');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'OU','Bilateral Eyes');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'BE','Bilateral Eyes');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'BN','Bilateral Nares ');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'BU','Buttock');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'CT','Chest Tube ');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LA','Left Arm');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LAC','Left Anterior Chest');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LACF','Left Antecubital Fossa');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LD','Left Deltoid');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LEJ','Left External Jugular');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'OS','Left Eye');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LF','Left Foot');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LG','Left Gluteus Medius');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LH','Left Hand');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LIJ','Left Internal Jugular');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LLAQ','Left Lower Abd Quadrant');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LLFA','Left Lower Forearm');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LMFA','Left Mid Forearm');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LN','Left Naris');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LPC','Left Posterior Chest');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LSC','Left Subclavian');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LT','Left Thigh');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LUA','Left Upper Arm');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LUAQ','Left Arm And Quadrant');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LUFA','Left Upper Forearm');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LVG','Left Ventragluteal');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'LVL','Left Vastus Lateralis');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'NB','Nebulized');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'PA','Perianal');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'PERIN','Perineal');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RA','Right Arm');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RAC','Right Anterior Chest');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RACF','Right Antecubital Fossa');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RD','Right Deltoid');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'REJ','Right External Jugular');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'OD','Right Eye');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RF','Right Foot');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RG','Right Gluteus Medius');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RH','Right Hand');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RIJ','Right Internal Jugular');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RLAQ','Rt Lower Abd Quadrant');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RLFA','Right Lower Forearm');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RMFA','Right Mid Forearm');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RN','Right Naris');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RPC','Right Posterior Chest');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RSC','Right Subclavian');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,2,'RT','Right Thigh');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RUA','Right Upper Arm');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RUAQ','Right Upper Abd Quadrant');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RUFA','Right Upper Forearm');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RVL','Right Vastus Lateralis');
insert into `site`(`IS_ACTIVE`,`VERSION`,`CODE`,`DESCRIPTION`) values (1,1,'RVG','Right Ventragluteal');