insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Cardiology','','0','Cardiology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Dermatology','','0','Dermatology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Emergency Medicine','','0','Emergency Medicine');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Endocrinology','','0','Endocrinology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Gastroenterology','','0','Gastroenterology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('General Family Practice','','0','General Family Practice');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Geriatrics','','0','Geriatrics');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Hematology-Oncology','','0','Hematology-Oncology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Infectious Diseases','','0','Infectious Diseases');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Nephrology','','0','Nephrology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Neurology','','0','Neurology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Obstetrics-Gynecology','','0','Obstetrics-Gynecology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Ophthalmology','','0','Ophthalmology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Orthopedics','','0','Orthopedics');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Otolaryngology','','0','Otolaryngology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Pediatrics','','0','Pediatrics');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Psychiatry','','0','Psychiatry');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Public Health','','0','Public Health');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Pulmonology','','0','Pulmonology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Rheumatology','','0','Rheumatology');
insert into `speciality` (`SPECIALITY_CODE`, `IS_ACTIVE`, `VERSION`, `DESCRIPTION`) values('Urology','','0','Urology');
