//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.05 at 04:21:44 PM IST 
//


package com.nzion.pqri;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Submission }
     * 
     */
    public Submission createSubmission() {
        return new Submission();
    }

    /**
     * Create an instance of {@link Submission.MeasureGroup }
     * 
     */
    public Submission.MeasureGroup createSubmissionMeasureGroup() {
        return new Submission.MeasureGroup();
    }

    /**
     * Create an instance of {@link Submission.MeasureGroup.Provider }
     * 
     */
    public Submission.MeasureGroup.Provider createSubmissionMeasureGroupProvider() {
        return new Submission.MeasureGroup.Provider();
    }

    /**
     * Create an instance of {@link Submission.FileAuditData }
     * 
     */
    public Submission.FileAuditData createSubmissionFileAuditData() {
        return new Submission.FileAuditData();
    }

    /**
     * Create an instance of {@link Submission.Registry }
     * 
     */
    public Submission.Registry createSubmissionRegistry() {
        return new Submission.Registry();
    }

    /**
     * Create an instance of {@link Submission.MeasureGroup.Provider.MeasureGroupStat }
     * 
     */
    public Submission.MeasureGroup.Provider.MeasureGroupStat createSubmissionMeasureGroupProviderMeasureGroupStat() {
        return new Submission.MeasureGroup.Provider.MeasureGroupStat();
    }

    /**
     * Create an instance of {@link Submission.MeasureGroup.Provider.PqriMeasure }
     * 
     */
    public Submission.MeasureGroup.Provider.PqriMeasure createSubmissionMeasureGroupProviderPqriMeasure() {
        return new Submission.MeasureGroup.Provider.PqriMeasure();
    }

}
