//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.05 at 04:21:44 PM IST 
//


package com.nzion.pqri;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Opening tag for submission element.
 *             
 * 
 * <p>Java class for pqriSubmission complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pqriSubmission">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="file-audit-data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="create-date" type="{}pqriDate"/>
 *                   &lt;element name="create-time" type="{}pqriTime"/>
 *                   &lt;element name="create-by">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="50"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="version">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="file-number" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="number-of-files" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="registry">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="registry-name">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="100"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="registry-id">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="9"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="submission-method" type="{}pqriSubmissionMethod"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="measure-group" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="provider" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="npi" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="waiver-signed" type="{}pqriYN"/>
 *                             &lt;element name="encounter-from-date" type="{}pqriDate"/>
 *                             &lt;element name="encounter-to-date" type="{}pqriDate"/>
 *                             &lt;element name="measure-group-stat">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ffs-patient-count" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                                       &lt;element name="group-reporting-rate-numerator" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                                       &lt;element name="group-eligible-instances" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                                       &lt;element name="group-reporting-rate" type="{}pqriPCt" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="pqri-measure">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="pqri-measure-number" type="{}pqriMeasureNum"/>
 *                                       &lt;element name="eligible-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="meets-performance-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="performance-exclusion-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="performance-not-met-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="reporting-rate" type="{}pqriPCt"/>
 *                                       &lt;element name="performance-rate" type="{}pqriPCt"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{}pqriMeasureGroup" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{}pqriSubmissionType" />
 *       &lt;attribute name="option" use="required" type="{}pqriSubmissionOption" />
 *       &lt;attribute name="version" use="required" type="{}pqriSubmissionVersion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pqriSubmission", propOrder = {
    "fileAuditData",
    "registry",
    "measureGroups"
})
@XmlRootElement(name = "submission")
public class Submission
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "file-audit-data", required = true)
    protected Submission.FileAuditData fileAuditData;
    @XmlElement(required = true)
    protected Submission.Registry registry;
    @XmlElement(name = "measure-group", required = true)
    protected List<Submission.MeasureGroup> measureGroups;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "option", required = true)
    protected String option;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the fileAuditData property.
     * 
     * @return
     *     possible object is
     *     {@link Submission.FileAuditData }
     *     
     */
    public Submission.FileAuditData getFileAuditData() {
        return fileAuditData;
    }

    /**
     * Sets the value of the fileAuditData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Submission.FileAuditData }
     *     
     */
    public void setFileAuditData(Submission.FileAuditData value) {
        this.fileAuditData = value;
    }

    public boolean isSetFileAuditData() {
        return (this.fileAuditData!= null);
    }

    /**
     * Gets the value of the registry property.
     * 
     * @return
     *     possible object is
     *     {@link Submission.Registry }
     *     
     */
    public Submission.Registry getRegistry() {
        return registry;
    }

    /**
     * Sets the value of the registry property.
     * 
     * @param value
     *     allowed object is
     *     {@link Submission.Registry }
     *     
     */
    public void setRegistry(Submission.Registry value) {
        this.registry = value;
    }

    public boolean isSetRegistry() {
        return (this.registry!= null);
    }

    /**
     * Gets the value of the measureGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measureGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasureGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Submission.MeasureGroup }
     * 
     * 
     */
    public List<Submission.MeasureGroup> getMeasureGroups() {
        if (measureGroups == null) {
            measureGroups = new ArrayList<Submission.MeasureGroup>();
        }
        return this.measureGroups;
    }

    public boolean isSetMeasureGroups() {
        return ((this.measureGroups!= null)&&(!this.measureGroups.isEmpty()));
    }

    public void unsetMeasureGroups() {
        this.measureGroups = null;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the option property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOption() {
        return option;
    }

    /**
     * Sets the value of the option property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOption(String value) {
        this.option = value;
    }

    public boolean isSetOption() {
        return (this.option!= null);
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="create-date" type="{}pqriDate"/>
     *         &lt;element name="create-time" type="{}pqriTime"/>
     *         &lt;element name="create-by">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="50"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="version">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="file-number" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="number-of-files" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "createDate",
        "createTime",
        "createBy",
        "version",
        "fileNumber",
        "numberOfFiles"
    })
    public static class FileAuditData
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "create-date", required = true)
        protected String createDate;
        @XmlElement(name = "create-time", required = true)
        protected String createTime;
        @XmlElement(name = "create-by", required = true)
        protected String createBy;
        @XmlElement(required = true)
        protected String version;
        @XmlElement(name = "file-number", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger fileNumber;
        @XmlElement(name = "number-of-files", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger numberOfFiles;

        /**
         * Gets the value of the createDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreateDate() {
            return createDate;
        }

        /**
         * Sets the value of the createDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreateDate(String value) {
            this.createDate = value;
        }

        public boolean isSetCreateDate() {
            return (this.createDate!= null);
        }

        /**
         * Gets the value of the createTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreateTime() {
            return createTime;
        }

        /**
         * Sets the value of the createTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreateTime(String value) {
            this.createTime = value;
        }

        public boolean isSetCreateTime() {
            return (this.createTime!= null);
        }

        /**
         * Gets the value of the createBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreateBy() {
            return createBy;
        }

        /**
         * Sets the value of the createBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreateBy(String value) {
            this.createBy = value;
        }

        public boolean isSetCreateBy() {
            return (this.createBy!= null);
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        public boolean isSetVersion() {
            return (this.version!= null);
        }

        /**
         * Gets the value of the fileNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFileNumber() {
            return fileNumber;
        }

        /**
         * Sets the value of the fileNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFileNumber(BigInteger value) {
            this.fileNumber = value;
        }

        public boolean isSetFileNumber() {
            return (this.fileNumber!= null);
        }

        /**
         * Gets the value of the numberOfFiles property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberOfFiles() {
            return numberOfFiles;
        }

        /**
         * Sets the value of the numberOfFiles property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberOfFiles(BigInteger value) {
            this.numberOfFiles = value;
        }

        public boolean isSetNumberOfFiles() {
            return (this.numberOfFiles!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="provider" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="npi" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="waiver-signed" type="{}pqriYN"/>
     *                   &lt;element name="encounter-from-date" type="{}pqriDate"/>
     *                   &lt;element name="encounter-to-date" type="{}pqriDate"/>
     *                   &lt;element name="measure-group-stat">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ffs-patient-count" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                             &lt;element name="group-reporting-rate-numerator" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                             &lt;element name="group-eligible-instances" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                             &lt;element name="group-reporting-rate" type="{}pqriPCt" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="pqri-measure">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="pqri-measure-number" type="{}pqriMeasureNum"/>
     *                             &lt;element name="eligible-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="meets-performance-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="performance-exclusion-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="performance-not-met-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="reporting-rate" type="{}pqriPCt"/>
     *                             &lt;element name="performance-rate" type="{}pqriPCt"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{}pqriMeasureGroup" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "providers"
    })
    public static class MeasureGroup
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "provider", required = true)
        protected List<Submission.MeasureGroup.Provider> providers;
        @XmlAttribute(name = "ID", required = true)
        protected String id;

        /**
         * Gets the value of the providers property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the providers property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProviders().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Submission.MeasureGroup.Provider }
         * 
         * 
         */
        public List<Submission.MeasureGroup.Provider> getProviders() {
            if (providers == null) {
                providers = new ArrayList<Submission.MeasureGroup.Provider>();
            }
            return this.providers;
        }

        public boolean isSetProviders() {
            return ((this.providers!= null)&&(!this.providers.isEmpty()));
        }

        public void unsetProviders() {
            this.providers = null;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

        public boolean isSetID() {
            return (this.id!= null);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="npi" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="tin" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="waiver-signed" type="{}pqriYN"/>
         *         &lt;element name="encounter-from-date" type="{}pqriDate"/>
         *         &lt;element name="encounter-to-date" type="{}pqriDate"/>
         *         &lt;element name="measure-group-stat">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ffs-patient-count" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *                   &lt;element name="group-reporting-rate-numerator" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *                   &lt;element name="group-eligible-instances" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *                   &lt;element name="group-reporting-rate" type="{}pqriPCt" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="pqri-measure">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="pqri-measure-number" type="{}pqriMeasureNum"/>
         *                   &lt;element name="eligible-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="meets-performance-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="performance-exclusion-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="performance-not-met-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="reporting-rate" type="{}pqriPCt"/>
         *                   &lt;element name="performance-rate" type="{}pqriPCt"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "npi",
            "tin",
            "waiverSigned",
            "encounterFromDate",
            "encounterToDate",
            "measureGroupStat",
            "pqriMeasure"
        })
        public static class Provider
            implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(required = true)
            protected BigInteger npi;
            @XmlElement(required = true)
            protected BigInteger tin;
            @XmlElement(name = "waiver-signed", required = true)
            protected String waiverSigned;
            @XmlElement(name = "encounter-from-date", required = true)
            protected String encounterFromDate;
            @XmlElement(name = "encounter-to-date", required = true)
            protected String encounterToDate;
            @XmlElement(name = "measure-group-stat", required = true)
            protected Submission.MeasureGroup.Provider.MeasureGroupStat measureGroupStat;
            @XmlElement(name = "pqri-measure", required = true)
            protected Submission.MeasureGroup.Provider.PqriMeasure pqriMeasure;

            /**
             * Gets the value of the npi property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNpi() {
                return npi;
            }

            /**
             * Sets the value of the npi property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNpi(BigInteger value) {
                this.npi = value;
            }

            public boolean isSetNpi() {
                return (this.npi!= null);
            }

            /**
             * Gets the value of the tin property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTin() {
                return tin;
            }

            /**
             * Sets the value of the tin property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTin(BigInteger value) {
                this.tin = value;
            }

            public boolean isSetTin() {
                return (this.tin!= null);
            }

            /**
             * Gets the value of the waiverSigned property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWaiverSigned() {
                return waiverSigned;
            }

            /**
             * Sets the value of the waiverSigned property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWaiverSigned(String value) {
                this.waiverSigned = value;
            }

            public boolean isSetWaiverSigned() {
                return (this.waiverSigned!= null);
            }

            /**
             * Gets the value of the encounterFromDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEncounterFromDate() {
                return encounterFromDate;
            }

            /**
             * Sets the value of the encounterFromDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEncounterFromDate(String value) {
                this.encounterFromDate = value;
            }

            public boolean isSetEncounterFromDate() {
                return (this.encounterFromDate!= null);
            }

            /**
             * Gets the value of the encounterToDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEncounterToDate() {
                return encounterToDate;
            }

            /**
             * Sets the value of the encounterToDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEncounterToDate(String value) {
                this.encounterToDate = value;
            }

            public boolean isSetEncounterToDate() {
                return (this.encounterToDate!= null);
            }

            /**
             * Gets the value of the measureGroupStat property.
             * 
             * @return
             *     possible object is
             *     {@link Submission.MeasureGroup.Provider.MeasureGroupStat }
             *     
             */
            public Submission.MeasureGroup.Provider.MeasureGroupStat getMeasureGroupStat() {
                return measureGroupStat;
            }

            /**
             * Sets the value of the measureGroupStat property.
             * 
             * @param value
             *     allowed object is
             *     {@link Submission.MeasureGroup.Provider.MeasureGroupStat }
             *     
             */
            public void setMeasureGroupStat(Submission.MeasureGroup.Provider.MeasureGroupStat value) {
                this.measureGroupStat = value;
            }

            public boolean isSetMeasureGroupStat() {
                return (this.measureGroupStat!= null);
            }

            /**
             * Gets the value of the pqriMeasure property.
             * 
             * @return
             *     possible object is
             *     {@link Submission.MeasureGroup.Provider.PqriMeasure }
             *     
             */
            public Submission.MeasureGroup.Provider.PqriMeasure getPqriMeasure() {
                return pqriMeasure;
            }

            /**
             * Sets the value of the pqriMeasure property.
             * 
             * @param value
             *     allowed object is
             *     {@link Submission.MeasureGroup.Provider.PqriMeasure }
             *     
             */
            public void setPqriMeasure(Submission.MeasureGroup.Provider.PqriMeasure value) {
                this.pqriMeasure = value;
            }

            public boolean isSetPqriMeasure() {
                return (this.pqriMeasure!= null);
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ffs-patient-count" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
             *         &lt;element name="group-reporting-rate-numerator" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
             *         &lt;element name="group-eligible-instances" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
             *         &lt;element name="group-reporting-rate" type="{}pqriPCt" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ffsPatientCount",
                "groupReportingRateNumerator",
                "groupEligibleInstances",
                "groupReportingRate"
            })
            public static class MeasureGroupStat
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(name = "ffs-patient-count")
                protected BigInteger ffsPatientCount;
                @XmlElement(name = "group-reporting-rate-numerator")
                protected BigInteger groupReportingRateNumerator;
                @XmlElement(name = "group-eligible-instances")
                protected BigInteger groupEligibleInstances;
                @XmlElement(name = "group-reporting-rate")
                protected Float groupReportingRate;

                /**
                 * Gets the value of the ffsPatientCount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getFfsPatientCount() {
                    return ffsPatientCount;
                }

                /**
                 * Sets the value of the ffsPatientCount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setFfsPatientCount(BigInteger value) {
                    this.ffsPatientCount = value;
                }

                public boolean isSetFfsPatientCount() {
                    return (this.ffsPatientCount!= null);
                }

                /**
                 * Gets the value of the groupReportingRateNumerator property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getGroupReportingRateNumerator() {
                    return groupReportingRateNumerator;
                }

                /**
                 * Sets the value of the groupReportingRateNumerator property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setGroupReportingRateNumerator(BigInteger value) {
                    this.groupReportingRateNumerator = value;
                }

                public boolean isSetGroupReportingRateNumerator() {
                    return (this.groupReportingRateNumerator!= null);
                }

                /**
                 * Gets the value of the groupEligibleInstances property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getGroupEligibleInstances() {
                    return groupEligibleInstances;
                }

                /**
                 * Sets the value of the groupEligibleInstances property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setGroupEligibleInstances(BigInteger value) {
                    this.groupEligibleInstances = value;
                }

                public boolean isSetGroupEligibleInstances() {
                    return (this.groupEligibleInstances!= null);
                }

                /**
                 * Gets the value of the groupReportingRate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Float }
                 *     
                 */
                public Float getGroupReportingRate() {
                    return groupReportingRate;
                }

                /**
                 * Sets the value of the groupReportingRate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Float }
                 *     
                 */
                public void setGroupReportingRate(Float value) {
                    this.groupReportingRate = value;
                }

                public boolean isSetGroupReportingRate() {
                    return (this.groupReportingRate!= null);
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="pqri-measure-number" type="{}pqriMeasureNum"/>
             *         &lt;element name="eligible-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="meets-performance-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="performance-exclusion-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="performance-not-met-instances" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="reporting-rate" type="{}pqriPCt"/>
             *         &lt;element name="performance-rate" type="{}pqriPCt"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "pqriMeasureNumber",
                "eligibleInstances",
                "meetsPerformanceInstances",
                "performanceExclusionInstances",
                "performanceNotMetInstances",
                "reportingRate",
                "performanceRate"
            })
            public static class PqriMeasure
                implements Serializable
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(name = "pqri-measure-number", required = true)
                protected String pqriMeasureNumber;
                @XmlElement(name = "eligible-instances", required = true)
                protected BigInteger eligibleInstances;
                @XmlElement(name = "meets-performance-instances", required = true)
                protected BigInteger meetsPerformanceInstances;
                @XmlElement(name = "performance-exclusion-instances", required = true)
                protected BigInteger performanceExclusionInstances;
                @XmlElement(name = "performance-not-met-instances", required = true)
                protected BigInteger performanceNotMetInstances;
                @XmlElement(name = "reporting-rate")
                protected float reportingRate;
                @XmlElement(name = "performance-rate")
                protected float performanceRate;

                /**
                 * Gets the value of the pqriMeasureNumber property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPqriMeasureNumber() {
                    return pqriMeasureNumber;
                }

                /**
                 * Sets the value of the pqriMeasureNumber property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPqriMeasureNumber(String value) {
                    this.pqriMeasureNumber = value;
                }

                public boolean isSetPqriMeasureNumber() {
                    return (this.pqriMeasureNumber!= null);
                }

                /**
                 * Gets the value of the eligibleInstances property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getEligibleInstances() {
                    return eligibleInstances;
                }

                /**
                 * Sets the value of the eligibleInstances property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setEligibleInstances(BigInteger value) {
                    this.eligibleInstances = value;
                }

                public boolean isSetEligibleInstances() {
                    return (this.eligibleInstances!= null);
                }

                /**
                 * Gets the value of the meetsPerformanceInstances property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getMeetsPerformanceInstances() {
                    return meetsPerformanceInstances;
                }

                /**
                 * Sets the value of the meetsPerformanceInstances property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setMeetsPerformanceInstances(BigInteger value) {
                    this.meetsPerformanceInstances = value;
                }

                public boolean isSetMeetsPerformanceInstances() {
                    return (this.meetsPerformanceInstances!= null);
                }

                /**
                 * Gets the value of the performanceExclusionInstances property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getPerformanceExclusionInstances() {
                    return performanceExclusionInstances;
                }

                /**
                 * Sets the value of the performanceExclusionInstances property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setPerformanceExclusionInstances(BigInteger value) {
                    this.performanceExclusionInstances = value;
                }

                public boolean isSetPerformanceExclusionInstances() {
                    return (this.performanceExclusionInstances!= null);
                }

                /**
                 * Gets the value of the performanceNotMetInstances property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getPerformanceNotMetInstances() {
                    return performanceNotMetInstances;
                }

                /**
                 * Sets the value of the performanceNotMetInstances property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setPerformanceNotMetInstances(BigInteger value) {
                    this.performanceNotMetInstances = value;
                }

                public boolean isSetPerformanceNotMetInstances() {
                    return (this.performanceNotMetInstances!= null);
                }

                /**
                 * Gets the value of the reportingRate property.
                 * 
                 */
                public float getReportingRate() {
                    return reportingRate;
                }

                /**
                 * Sets the value of the reportingRate property.
                 * 
                 */
                public void setReportingRate(float value) {
                    this.reportingRate = value;
                }

                public boolean isSetReportingRate() {
                    return true;
                }

                /**
                 * Gets the value of the performanceRate property.
                 * 
                 */
                public float getPerformanceRate() {
                    return performanceRate;
                }

                /**
                 * Sets the value of the performanceRate property.
                 * 
                 */
                public void setPerformanceRate(float value) {
                    this.performanceRate = value;
                }

                public boolean isSetPerformanceRate() {
                    return true;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="registry-name">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="100"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="registry-id">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="9"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="submission-method" type="{}pqriSubmissionMethod"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "registryName",
        "registryId",
        "submissionMethod"
    })
    public static class Registry
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "registry-name", required = true)
        protected String registryName;
        @XmlElement(name = "registry-id", required = true)
        protected String registryId;
        @XmlElement(name = "submission-method", required = true)
        protected String submissionMethod;

        /**
         * Gets the value of the registryName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegistryName() {
            return registryName;
        }

        /**
         * Sets the value of the registryName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegistryName(String value) {
            this.registryName = value;
        }

        public boolean isSetRegistryName() {
            return (this.registryName!= null);
        }

        /**
         * Gets the value of the registryId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegistryId() {
            return registryId;
        }

        /**
         * Sets the value of the registryId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegistryId(String value) {
            this.registryId = value;
        }

        public boolean isSetRegistryId() {
            return (this.registryId!= null);
        }

        /**
         * Gets the value of the submissionMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubmissionMethod() {
            return submissionMethod;
        }

        /**
         * Sets the value of the submissionMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubmissionMethod(String value) {
            this.submissionMethod = value;
        }

        public boolean isSetSubmissionMethod() {
            return (this.submissionMethod!= null);
        }

    }

}
