package com.nzion.enums;

public enum AutomaticAssignmentType {
       PATIENT_CODE,ATTORNEY_CODE,INSURANCE_CODE,PROVIDER_CODE,LOCATION_CODE,PCP_CODE,ADJUSTER_CODE,CASE_MANAGER_CODE,
	   REFERRING_PHYSICIAN_CODE,SCHOOL_CODE,VENDOR_CODE,MEDICATION_CODE,ACCOUNT_STATUS_CODE,EMPLOYER_CODE,GUARANTOR_CODE;
}