package com.nzion.enums;

public enum PatientEntryDefaultsType {
     CITY_DEFINITION,STATE_DEFINITION,POSTAL_CODE,GENDER_DEFINITION,SIGN_ON_FILE,RELEASE_INFO,DOB_CENTURY,
	 STATEMENT_FORM,STATEMENT_METHOD,RECALL_METHOD,FINANCIAL_CLASS,PHYSICIAN_LOOKUP,LOCATION_LOOKUP,COUNTRY_CODE,AREA_CODE;
}