package com.nzion.enums;

public enum ProviderPreferences {
	HPI_VIEW, PAST_HISTORY, EXAMINATION, MEDICATION_REPORT, PHCALERT_SOAP, PATIENT_TRACKING, 
	DIFF_DIAGNOSIS_SETUP, PASTHISTORY_ALERT, PATIENTSSN_SOAP, PATIENTREFPHYSICIAN_SOAP, 
	TREATMENTPLAN_RECOMMENDATION, NORMALSENTENCE_QAMODULES, PEDIATRICGRAPH_SOAPNOTES, 
	PROVIDER_VITAL_SIGNS, PRACTICENAME_SOAP, LOCATIONNAME_SOAP, PROVIDER_BASE_TEMP, 
	ROS_VIEW, SOCIAL_HISTORY, RECOMMENDATION_VIEW, DISPLAY_BMI, PEDIATRIC_BMI, 
	DISPLAY_BSA, DISPLAY_SS_SIGNIN, ABN_SERVICE_VERIFICATION, BMI_BSA_VALUES, 
	DIAGNOSIS_TREESEARCH, PRINTSOAPNOTE_SIGNOFF, PROVIDER_FAMILYHISTORY, DEFAULTVALUE_VITALSIGN, 
	CPT_REFERRALLETTER, DEA_RXREPORT, LOCATIONDEANUMBER_RXREPORT, STATELICENSE_RXREPORT, 
	PROVIDERNAME_RXREPORT, PRACTICENAME_RXREPORT, LOCATIONNAME_RXREPORT, NPINUMBER_RXREPORT;
}
