package com.nzion.enums;

public enum ProviderPrescriptions {
    DEA_RXREPORT,LOCATIONDEANUMBER_RXREPORT,STATELICENSE_RXREPORT,PROVIDERNAME_RXREPORT,PRACTICENAME_RXREPORT,
	LOCATIONNAME_RXREPORT,NPINUMBER_RXREPORT;
	}